---
- hosts: localhost
  name: Teste Cenário Inventory in Memory
  gather_facts: true
  tasks:

    - name: create inventory in memory
      add_host:
        hostname: "{{ IP_HOST }}"
        group: "{{ GROUPS }}"

- name: Collect Facts by "{{ GROUPS }}"
  hosts: "{{ GROUPS }}"
  gather_facts: true
  roles:
    - satellite