---
- set_fact:
    FNAME: "{{ ansible_facts.hostname }}"
    
- set_fact:
    FHOSTNAME: "{{ ansible_facts.fqdn }}"

- set_fact:
    FIP: "{{ ansible_facts.default_ipv4.address }}"

- name: Find out what the remote machine's mounts are
  slurp:
    src: /etc/os-release
  register: release

- set_fact:
    decode: "{{ release['content'] | b64decode }}"

- name: Obter as variaveis de /etc/os-release
  set_fact: 
    content: "{{ decode.splitlines() }}"

- set_fact: 
    OSNAME: "{{ item[6].split('=')[1] }}"
  loop: 
    - "{{ content }}"

- set_fact: 
    VARIANT: "{{ item[6].split('=')[1] | replace('\"','') }}"
  loop: 
    - "{{ content }}"

- set_fact: 
    VERSION: "{{ item[4].split('=')[1] | replace('\"','') }}"
  loop: 
    - "{{ content }}"

- debug:
    msg:
      - "{{ FNAME }}"
      - "{{ FHOSTNAME }}"
      - "{{ FIP }}"
      - "{{ OSNAME }}"
      - "{{ VARIANT | replace('\"','') }}"
      - "{{ VERSION | replace('\"','') }}"